version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - postgres
    networks:
      - internal

  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - postgres/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - internal
      - external

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/lib/letsencrypt -d workwithmove.com --email your@email.com --agree-tos --no-eff-email
    networks:
      - external

volumes:
  pgdata:
  certbot-etc:
  certbot-var:

networks:
  internal:
  external: